language: c
dist: trusty
sudo: required

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake && sudo apt-get install -y cpputest && sudo apt-get install -y gcc && sudo apt-get install -y pkg-config
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
