language: c
dist: trusty

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # - george-edison55-precise-backports
    packages:
      - cmake
      - gcc
      - g++
      - pkg-config
      - cpputest

script:
  - mkdir build && cd build
  - cmake ..
  - make && make test
