language: c
dist: trusty
sudo: required

compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev
      
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake && sudo apt-get install -y cpputest && sudo apt-get install -y gcc && sudo apt-get install -y pkg-config
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
