language: c
dist: trusty
sudo: true

compiler:
  - gcc

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#       # - george-edison55-precise-backports
#     packages:
#       - cmake
#       - gcc
#       - g++
#       - pkg-config
#       - cpputest

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -y cmake &&
    sudo apt-get install -y gcc &&
    sudo apt-get install -y g++ &&
    sudo apt-get install -y pkg-config &&
    sudo apt-get install -y cpputest
script:
  - mkdir build && cd build
  - cmake ..
  - make && make test
