language: c
dist: trusty

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - libc++-dev
      - cmake-data
      - cmake
      - time
      - cpputest
      - pkg-config
      - gcc
      - g++

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
